# Generated by Django 6.0.5 on 2026-07-02 23:57

import uncial_wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoarticlepage',
            name='body',
            field=uncial_wagtail.fields.UncialField(blank=True, default=uncial_wagtail.fields.empty_uncial_document),
        ),
    ]
